server:
  port: 9980

spring:
  datasource:
    url: jdbc:mysql://192.168.3.54:3306/bcwl_base?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: bcwl_base
    password: bcwl_base+ar5m
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.mybatis.generator.domain
